#Independent settings for the global planner's costmap. Detailed descriptions of these parameters can be found at http://www.ros.org/wiki/costmap_2d

global_costmap:
 global_frame: /map
 robot_base_frame: base_link
 update_frequency: 1.0
 publish_frequency: 0.5
 static_map: true
 transform_tolerance: 0.5
